import { fetchNewsAPI } from '@/lib/news-api';
import PowerPlayFeed from '@/components/PowerPlayFeed';

import { CrosscheckHeader } from '@/components/CrosscheckHeader';
import PowerPlayNavigation from '@/components/PowerPlayNavigation';

// Force dynamic rendering since we are fetching live data
export const dynamic = 'force-dynamic';
export const revalidate = 1800; // 30 minutes

export default async function PowerPlayPage() {
    const articles = await fetchNewsAPI();

    return (
        <main className="min-h-screen bg-[#050505] text-[#ededed] font-mono selection:bg-purple-500 selection:text-black">
            <CrosscheckHeader />
            <PowerPlayNavigation />

            <div className="container mx-auto px-4 py-12 max-w-[1600px]">
                {/* Hero Section */}
                <div className="mb-16 relative">
                    <div className="absolute -left-4 top-0 bottom-0 w-1 bg-gradient-to-b from-purple-500 to-transparent" />
                    <div className="pl-6">
                        <div className="flex items-center gap-4 mb-4">
                            <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-white">
                                POWER PLAY PRESS
                            </h1>
                            <div className="bg-zinc-900 border border-zinc-800 px-4 py-1 rounded-full text-zinc-400 text-sm font-mono flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                                {articles.length} SOURCES LIVE
                            </div>
                        </div>
                        <p className="text-xl text-zinc-500 max-w-2xl font-light">
                            Real-time intelligence feed tracking the Minnesota fraud ecosystem.
                            Aggregated from mainstream media, court filings, and social signals.
                        </p>
                    </div>

                    {/* Decorative Background Elements */}
                    <div className="absolute top-0 right-0 w-96 h-96 bg-purple-900/10 blur-[100px] rounded-full pointer-events-none" />
                </div>

                {/* Main Feed */}
                <PowerPlayFeed initialArticles={articles} />
            </div>

            <footer className="mt-20 border-t border-zinc-900 py-12 text-center text-zinc-600 font-mono text-xs">
                <p>GENERATED BY PROJECT CROSSCHECK INTELLIGENCE CORE</p>
            </footer>
        </main>
    );
}
