import { fetchNewsAPI } from '@/lib/news-api';
import PowerPlayFeed from '@/components/PowerPlayFeed';
import { Newspaper } from 'lucide-react';
import { CrosscheckHeader } from '@/components/CrosscheckHeader';

// Force dynamic rendering since we are fetching live data
export const dynamic = 'force-dynamic';
export const revalidate = 1800; // 30 minutes

export default async function PowerPlayPage() {
    const articles = await fetchNewsAPI();

    return (
        <main className="min-h-screen bg-[#050505] text-[#ededed] font-mono selection:bg-purple-500 selection:text-black">
            {/* We reuse the header or a dedicated one? Reusing the main one is safer for consistency, 
                 but it might include nav we don't want if it's tied to activeTab state.
                 For now, I'll just build a standalone header for this 'press' section to ensure it looks premium. 
              */}

            <header className="border-b border-white/10 bg-black/50 backdrop-blur-md sticky top-0 z-40">
                <div className="container mx-auto px-4 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <div className="w-8 h-8 bg-purple-600 rounded flex items-center justify-center">
                            <span className="font-bold text-black text-xl">P</span>
                        </div>
                        <span className="font-bold text-lg tracking-wider">PROJECT CROSSCHECK</span>
                    </div>
                    <div className="flex items-center gap-4 text-xs font-mono text-zinc-500">
                        <span>EST. 2025</span>
                        <div className="h-4 w-px bg-zinc-800" />
                        <span className="text-purple-400">RESTRICTED ACCESS</span>
                    </div>
                </div>
            </header>

            <div className="container mx-auto px-4 py-12 max-w-[1600px]">
                {/* Hero Section */}
                <div className="mb-16 relative">
                    <div className="absolute -left-4 top-0 bottom-0 w-1 bg-gradient-to-b from-purple-500 to-transparent" />
                    <div className="pl-6">
                        <div className="flex items-center gap-4 mb-4">
                            <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-white">
                                POWER PLAY PRESS
                            </h1>
                            <div className="bg-zinc-900 border border-zinc-800 px-4 py-1 rounded-full text-zinc-400 text-sm font-mono flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                                {articles.length} SOURCES LIVE
                            </div>
                        </div>
                        <p className="text-xl text-zinc-500 max-w-2xl font-light">
                            Real-time intelligence feed tracking the Minnesota fraud ecosystem.
                            Aggregated from mainstream media, court filings, and social signals.
                        </p>
                    </div>

                    {/* Decorative Background Elements */}
                    <div className="absolute top-0 right-0 w-96 h-96 bg-purple-900/10 blur-[100px] rounded-full pointer-events-none" />
                </div>

                {/* Main Feed */}
                <PowerPlayFeed initialArticles={articles} />
            </div>

            <footer className="mt-20 border-t border-zinc-900 py-12 text-center text-zinc-600 font-mono text-xs">
                <p>GENERATED BY PROJECT CROSSCHECK INTELLIGENCE CORE</p>
            </footer>
        </main>
    );
}
